### ISSUE TITLE
Issues with Vanetza build 

### ISSUE THREAD

**Issue by MattiaAndreani** [riebl/vanetza#177]
Hi all, 
I am a new user to Vanetza. I have downloaded and built Vanetza, following the instructions reported on the main page. The build has completed successfully and also the tests have been successful. Yet, when I try to include some modules (e.g. #include <vanetza/security/backend.hpp>) in a main.cpp script, I get an error saying that some header files do not exist. Moreover, when I try to import Vanetza targets as Vanetza::vanetza (such as specified in the main page) I get an error saying that Vanetza has not been defined. I wanted to know if there is maybe some problems with the build or if I am making some other technical errors. 
I have inserted the main.cpp script in the folder in which the build has been performed.

Thank you in advance!

**Comment by riebl** [comment]
Hi @MattiaAndreani,

I think your build setup is not correct. First, you should put your *main.cpp* in a project folder of your choice but not in the build directory. You should consider the build directory as a temporary location. Next to your *main.cpp* you have to put a *CMakeLists.txt* which should look similar to the following snippet:

```
project(YourProjectName)
find_package(Vanetza REQUIRED)
add_executable(your_executable main.cpp)
target_link_libraries(your_executable Vanetza::vanetza)
```

Furthermore, you may want to enable `CMAKE_EXPORT_PACKAGE_REGISTRY` in Vanetza's build directory as described here: https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_PACKAGE_REGISTRY.html
Otherwise, the automatic find mechanism of your Vanetza build directory by your project's `CMakeLists.txt` won't work.
Using the package registry is not required but is often convenient. Alternatively, you need to manually specify in your project's build directory where it can find the Vanetza build directory.

**Comment by MattiaAndreani** [comment]
@riebl thank you very much for these clarifications. I will try to follow them and see if the issues are solved
