### ISSUE TITLE
check_generation_time too strict

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#19]
It seems like [`check_generation_time`](https://github.com/riebl/vanetza/blob/616fb558dd297fc74886e117c7592e19833bc958/vanetza/security/verify_service.cpp#L16-L46) is too strict.

https://github.com/riebl/vanetza/blob/616fb558dd297fc74886e117c7592e19833bc958/vanetza/security/verify_service.cpp#L25

That requires clocks to be out-of-sync no more than 40 milliseconds, otherwise that check fails.

Currently I hit that even locally with the same clock, but because of a different issue: the clock is currently only updated in each `Runtime` tick.

**Comment by riebl** [comment]
I have just checked the BSP document and noticed that `generation_time_past_ca` should be 2 seconds instead of 2 minutes (fixed in 88dcd9654c5d50387fcb5db078e30e92e65ee016). However, the limit of 40 ms is quite clearly given.
Thus, I assume the issue is not `generation_time_future` but maybe a stale clock? Do you experience this issue with already published or new code? This might help to track down the problem.

**Comment by kelunik** [comment]
I can open a PR with the code I have. It needs some clean up, but I can push it and fix it before it's merged. As said, I definitely hit that issue because of a stale clock, but opened an issue, because I think it might be a more general concern. Two clocks on the same system can't be out of sync without one being stale, but I guess clocks being out of sync for more than 40 milliseconds might happen in a real world scenario.

Do you know what the reason for a higher `time_past` than `time_future` is? I guess this might be due to the time required for sending the messages (potentially over multiple hops).

Do you have a link to the document? I wasn't able to find a public version of it.

**Comment by riebl** [comment]
In real world scenarios ITS stations are expected to synchronize theirs clocks using GNSS, i.e. even with temporary GNSS signal loss its hardly possible to have a clock bias of several tens of milliseconds.
I am not aware of the reasoning behind the past and future time limits but potential delays due to packet buffering are definitely one of the reasons. Unfortunately, there is no public version of the document available to the best of my knowledge. I am not even sure if I were allowed to disclose parts of it.
Back to your problem: I assume there is a bug concerning the update of `Runtime` with recent time points. Please create a PR with your code.

**Comment by kelunik** [comment]
I'll create the PR tomorrow.

**Comment by riebl** [comment]
Possible solution: Add another `trigger_.schedule()` before calling `router_.indicate(...)` in router_context.cpp:75. The first call will update the clock reading for the security entity, the second (already existing) call schedules packet forwarding.
Can you please check if this fixes the problem?

**Comment by kelunik** [comment]
That seems to fix it, yes. I've opened #21.

**Comment by riebl** [comment]
Merged 87e88cf2876dd1e7b7d31f3c95a5df1336aa8b11

**Comment by kelunik** [comment]
Just adding http://oldforge.etsi.org/mantis/view.php?id=6987 as further reference.
