### ISSUE TITLE
Missing dependencies (documentation)

### ISSUE THREAD

**Issue by namnatulco** [riebl/vanetza#2]
Hi!
I just made a first build (to be precise, using the current artery master branch) and noticed some dependencies are missing in the README file:
 - CryptoPP
 - asn1c

I also saw some output regarding the Cohda SDK, which I initially thought caused compilation failures, but it seems that's not an issue.

For Fedora users, this (I think) gives a complete setup:
`dnf install gcc-c++ cmake boost-devel GeographicLib-devel cryptopp-devel asn1c`

**Comment by riebl** [comment]
Hi,

thanks for your feedback! In fact, I will have to update the README reflecting the recently published security features. asn1c is not strictly required anymore because a pre-generated copy of the CA and DEN messages is now included and should be used automatically when no asn1c is found on the system.

I would also be very happy if you could provide some feedback about your experiences regarding Vanetza!

Best regards,
Raphael

**Comment by namnatulco** [comment]
For some reason I did encounter a compilation failure without `asn1c`. I'll go reproduce it and let you know. Our research group is currently considering using artery as part of an exercise with a focus on security and geonetworking. I'll try and report any issues I find.

**Comment by namnatulco** [comment]
[here](https://gist.github.com/namnatulco/12ecd43dd6fba68ff755b172b6d89624#file-output-txt) is the compilation output without `asn1c` (I simply removed it, removed the `build` folder, recreated that, then ran `cmake .. && cmake --build .` in the new build folder). [Here](https://gist.github.com/namnatulco/12ecd43dd6fba68ff755b172b6d89624#file-cmakeoutput-log) is the associated log file. Unfortunately I'm not familiar enough with CMake to debug what's going wrong.

**Comment by riebl** [comment]
Should be fixed with  1d4b9cd. Thank you for reporting this issue!
