### ISSUE TITLE
Change description to exclude G5

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#31]
Currently the repository description says _"Open-source implementation of the ETSI ITS-G5 protocol stack"_. If I got it correctly, ITS-G5 only refers to the short-range wireless communication (the access layer). It might be better to just say _"Open-source implementation of the ETSI ITS protocol stack"_?

**Comment by kelunik** [comment]
Maybe also ITS-GN protocol stack.

**Comment by riebl** [comment]
I am afraid that the term "ETSI ITS" is too broad because ITS covers also standards such as MirrorLink and electronic fee collection. Both will most likely never be implemented by Vanetza. According to http://www.etsi.org/technologies-clusters/technologies/automotive-intelligent-transport the term "ETSI C-ITS" may be fitting when speaking about the whole stack. However, there are also numerous sources using "ITS-G5" when speaking about ETSI V2X, e.g. https://www.2025ad.com/latest/its-g5-driverless-cars/ (saying ITS-G5 is WAVE's sister).
Still have to think a little bit about this but for sure there is no clear taxonomy.

**Comment by kelunik** [comment]
I came across this issue while trying to find a good title for my Bachelor's thesis. C-ITS might be a good fit, but also ETSI V2X.

_"Open-source implementation of the ETSI V2X protocol stack for C-ITS."_

**Comment by riebl** [comment]
Changed to "ETSI C-ITS protocol stack" and an updated introduction in the README, see 28c75a4cef0172536d10c3db5dfcd0a3e6b9fc94
