### ISSUE TITLE
Couldn't able to send CAM message using socktap

### ISSUE THREAD

**Issue by srilekha-tcs** [riebl/vanetza#76]
I am trying to send CAMs using socktap-cam and I am also using gpsfake to give all the gps related data. GPS data is being fed as input but CAMs are not getting generated , instead it is showing like 
" sent packet to ff:ff:ff:ff:ff:ff (50 bytes)
  Skipping CAM, because no good position is available, yet.
  Skipping CAM, because no good position is available, yet.
  Skipping CAM, because no good position is available, yet.
  Skipping CAM, because no good position is available, yet. " . This result is shown repeatedly.  
I am not sure how to proceed further. Can I get any information regarding position.confidence also?

**Comment by riebl** [comment]
`position.confidence` is copied from gpsd's `gps_fix_t` data structure in *gps_position_provider.cpp*. You should provide (or fake) `epx` and `epy` values as well, however, I don't know whether *gpsfake* supports this.

**Comment by srilekha-tcs** [comment]
Yes, gpsfake will not give information about epx and epy. Are there any tools to generate the data of epx and epy. Please help me with it.

**Comment by riebl** [comment]
Feel free to change Vanetza's source code in any way you want. As a very basic workaround you may simply set a fixed position confidence (semi_minor, semi_major, and orientation) in *gps_position_provider.cpp*.
I am closing this issue ticket because it does not describe a bug of Vanetza but a feature limitation of gpsfake. A pull request extending socktap is welcome.
